name: Test canboatjs dependents

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  build_and_test:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout canboatjs
      uses: actions/checkout@v4
      with:
        path: ./canboatjs
  
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        
    - name: Build canboatjs
      run: |
        npm install
        npm run build
        npm link
      working-directory: ./canboatjs

    - name: Checkout n2k-signalk
      uses: actions/checkout@v4
      with:
        repository: SignalK/n2k-signalk
        path: ./n2k-signalk

    - name: Build & Test n2k-signalk
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
        npm test
      working-directory: ./n2k-signalk

    - name: Checkout signalk-to-nmea2000
      uses: actions/checkout@v4
      with:
        repository: SignalK/signalk-to-nmea2000
        ref: typescript
        path: ./signalk-to-nmea2000

    - name: Build & Test signalk-to-nmea2000
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
        npm test
      working-directory: ./signalk-to-nmea2000

    - name: Checkout signalk-n2k-switching
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-switching
        path: ./signalk-n2k-switching

    - name: Build signalk-n2k-switching
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-n2k-switching

    - name: Checkout signalk-n2k-displays
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-displays
        path: ./signalk-n2k-displays

    - name: Build signalk-n2k-displays
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
      working-directory: ./signalk-n2k-displays

    - name: Checkout signalk-n2k-switching-emulator
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-switching-emulator
        ref: main
        path: ./signalk-n2k-switching-emulator

    - name: Build signalk-n2k-switching-emulator
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
      working-directory: ./signalk-n2k-switching-emulator

    - name: Checkout signalk-alarm-silencer
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-alarm-silencer
        ref: ts-pgns
        path: ./signalk-alarm-silencer

    - name: Build signalk-alarm-silencer
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
      working-directory: ./signalk-alarm-silencer

    - name: Checkout signalk-fusion-stereo
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-fusion-stereo
        ref: master
        path: ./signalk-fusion-stereo

    - name: Build signalk-fusion-stereo
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
      working-directory: ./signalk-fusion-stereo

    - name: Checkout signalk-yd-alarm-button
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-yd-alarm-button
        ref: ts-pgns
        path: ./signalk-yd-alarm-button

    - name: Build signalk-yd-alarm-button
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
      working-directory: ./signalk-yd-alarm-button

    - name: Checkout signalk-n2kais-to-nmea0183
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2kais-to-nmea0183
        path: ./signalk-n2kais-to-nmea0183

    - name: Build signalk-n2kais-to-nmea0183
      run: |
        npm install
        npm link @canboat/canboatjs
        npm run build
        npm test
      working-directory: ./signalk-n2kais-to-nmea0183

    - name: Checkout signalk-autopilot
      if: always()
      uses: actions/checkout@v4
      with:
        repository: SignalK/signalk-autopilot
        path: ./signalk-autopilot

    - name: Build signalk-autopilot
      id: test_signalk_autopilot
      if: always()
      run: |
        npm install
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./signalk-autopilot

